### ISSUE TITLE
Cannot login trought svelte

### ISSUE THREAD

**Issue by SymonRod** [mm-io/hasura-django-starter#19]
Hi!
I was trying to use your template for experimenting with Hasura and Django, but when i try to login at "http://127.0.0.1:8088/login", it gave me this error.

![image](https://user-images.githubusercontent.com/46075611/210323171-b07b4305-0e48-4908-86b9-c24fbad08c94.png)

I try to login with the django rest interface at [127.0.0.1:8000](http://127.0.0.1:8000/api/login/) with the same credentials and it works.

![image](https://user-images.githubusercontent.com/46075611/210324025-01e9291c-0ea2-49ea-94c0-1516ac1d8e2a.png)

I followed your instruction in the readme but nothing.

Hope you can help me :smile:

**Comment by SymonRod** [comment]
I found out what the issue was.

In the Hasura metadata the handler was defined as: 
``` yaml
handler: http://host.docker.internal:8000  
```
I changed to:
``` yaml
handler: http://django:8000
```

And now it work.

I changed to "http://django:8000" because when dockers are in the same docker compose you can use their service name defined in the docker-compose.yml

**Comment by m-rgba** [comment]
That's interesting, it should work (and works on my side) since the `host.docker.internal ` is pretty much just the internal network created by Docker - I can have a look at that.

Glad you found `django` also works as the service name to connect to over the network. Pretty sure `localhost` or `127.0.0.1` should also work in the action configuration for this specific demo since the port is exposed locally.

One improvement I could make as well is to set each of the Hasura Actions to the same host and then use the transforms for each of the routes (like `/api/login`).
For the host we could load it in from an env variable, so changing one entry in the docker-compose file would update the hostname for all of the Actions in the demo in case anyone else has problems (also if you ever wanted to deploy this since the Hasura instance and Django instance may not always be on the same host).
